destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/manual-pdf"
port: 4010
output: pdf
product: manual
print_title: Inviwo Documentation
print_subtitle: version 6.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: manual_sidebar
